services:
  - type: web
    name: calculadoras-portugal-2026
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: FLASK_ENV
        value: production